name: Flutter CI

on: [ push ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version-file: pubspec.yaml
          channel: 'stable'
      - name: Analyze code
        run: flutter analyze
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version-file: pubspec.yaml
          channel: 'stable'
      - name: Run tests
        run: flutter test
  build:
   runs-on: ubuntu-latest
   container:
     image: werockstar/android-build:0.0.1-alpha06
   steps:
     - name: build
       run: bundler exec fastlane android build
